### PR TITLE
Regenerate VSM and fix tricked_out example

### LINKED ISSUE #6: tricked_out example not working
This example has never worked on ps2sdk. I'm very curious what it looks like ;).

### PR DESCRIPTION
**Pull request by rickgaiser**
Fixes #6

### CODE REVIEW

File: examples/tricked_out/billboard_renderer.h [hunk 1]
```diff
@@ -7,7 +7,7 @@
 #ifndef bb_renderer_h
 #define bb_renderer_h
 
-#include "ps2s/matrix.h"
+//#include "ps2s/matrix.h"
```
Comment (fjtrujy) [inline examples/tricked_out/billboard_renderer.h:10]: just remove it better, right?

**Comment by fjtrujy** [comment]
That's a really good news!!!
Thanks @rickgaiser !!
We should also add this example in the CI.
